[tool.poetry]
name = "polygpt"
version = "0.1.0"
description = "polygpt runs ai dao"
authors = ["Prinecps Polaris <polycapn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
